version: "3.1"
services:
  peppermint_postgres:
    container_name: peppermint_postgres
    image: postgres:latest
    restart: always
    volumes:
      - pgdata_live:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
  peppermint:
    container_name: peppermint
    image: pepperlabs/peppermint:latest
    ports:
      - 1000:3000
      - 1001:5003
    restart: always
    depends_on:
      - peppermint_postgres
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      SECRET: ${SECRET}
    volumes:
      - peppermint_data:/data   # <-- Example: Mount /data inside the container
volumes:
  pgdata_live:
  peppermint_data:    # <-- Declare the new volume
